{"uuid": "e0bbc464-f83e-4c41-8c68-11e4b4f42ad3", "children": ["bee9fbb5-3b7c-4c56-bf3e-bacc709efe12", "b8d0fe40-87f6-4db0-81aa-5876660ae103"], "befores": [{"name": "login_new_user", "status": "broken", "statusDetails": {"message": "Exception: Не удалось зарегистрировать пользователя и получить токены.\n", "trace": "  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\conftest.py\", line 47, in login_new_user\n    raise Exception(\"Не удалось зарегистрировать пользователя и получить токены.\")\n"}, "steps": [{"name": "Регистрация и авторизация нового пользователя через API, возвращение авторизационных данных", "status": "passed", "steps": [{"name": "Генерация данных пользователя", "status": "passed", "start": 1730125030628, "stop": 1730125030629}], "start": 1730125030628, "stop": 1730125031022}], "start": 1730125030627, "stop": 1730125031022}], "start": 1730125030627, "stop": 1730125031033}