{"uuid": "94e4f797-c336-4ec4-b2e3-d138b09e6d54", "children": ["f6f838ec-34b2-42f6-af88-f17d37f15a92"], "befores": [{"name": "login_new_user", "status": "broken", "statusDetails": {"message": "Exception: Не удалось зарегистрировать пользователя и получить токены.\n", "trace": "  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_3\\conftest.py\", line 47, in login_new_user\n    raise Exception(\"Не удалось зарегистрировать пользователя и получить токены.\")\n"}, "steps": [{"name": "Регистрация и авторизация нового пользователя через API, возвращение авторизационных данных", "status": "passed", "steps": [{"name": "Генерация данных пользователя", "status": "passed", "start": 1730127330882, "stop": 1730127330885}], "start": 1730127330882, "stop": 1730127331225}], "start": 1730127330882, "stop": 1730127331225}], "start": 1730127330882, "stop": 1730127331240}